-- -------------------------------------------------------------
-- TablePlus 5.6.2(516)
--
-- https://tableplus.com/
--
-- Database: procesos
-- Generation Time: 2023-12-18 10:30:33.5650
-- -------------------------------------------------------------


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


CREATE TABLE `calculo` (
  `ID_Calculo` int(11) NOT NULL AUTO_INCREMENT,
  `ID_Actividad` int(11) NOT NULL,
  `nom_actividad` varchar(50) NOT NULL,
  `Tiempo` varchar(50) NOT NULL,
  `ID_Valor` int(11) NOT NULL,
  `Nom_Valor` varchar(50) NOT NULL,
  `Nom_frecuencia` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_Calculo`),
  KEY `ID_Actividad` (`ID_Actividad`),
  KEY `ID_Valor` (`ID_Valor`),
  CONSTRAINT `calculo_ibfk_1` FOREIGN KEY (`ID_Actividad`) REFERENCES `detalle_actividad` (`ID_Actividad`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `calculo_ibfk_2` FOREIGN KEY (`ID_Valor`) REFERENCES `frecuencia` (`ID_Valor`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

CREATE TABLE `consultas` (
  `ID` int(11) NOT NULL,
  `val_Frec` varchar(100) NOT NULL,
  `input` varchar(100) NOT NULL,
  `sistema` varchar(100) NOT NULL,
  `rol` varchar(100) NOT NULL,
  `tiempo` varchar(100) NOT NULL,
  `vol` varchar(100) NOT NULL,
  `t_h` varchar(100) NOT NULL,
  `ftes` varchar(100) NOT NULL,
  `estado` varchar(5) NOT NULL,
  `username_id` int(11) DEFAULT 0,
  `procesos_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

CREATE TABLE `detalle_actividad` (
  `ID_Actividad` int(11) NOT NULL AUTO_INCREMENT,
  `nom_actividad` varchar(120) NOT NULL,
  `Entregable` varchar(50) NOT NULL,
  `sistema` varchar(50) NOT NULL,
  `Descripcion` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_Actividad`)
) ENGINE=InnoDB AUTO_INCREMENT=171 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

CREATE TABLE `direcciones` (
  `ID_Direccion` int(11) NOT NULL AUTO_INCREMENT,
  `Nom_Direccion` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_Direccion`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

CREATE TABLE `entrega` (
  `ID_entrega` int(11) NOT NULL AUTO_INCREMENT,
  `nom_entrega` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_entrega`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

CREATE TABLE `eventos` (
  `ID_Eventos` int(11) NOT NULL AUTO_INCREMENT,
  `Eventual` varchar(50) NOT NULL,
  `Por_Eventos` varchar(50) NOT NULL,
  `Continuos` varchar(50) NOT NULL,
  `Mensual` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_Eventos`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

CREATE TABLE `frecuencia` (
  `ID_Valor` int(11) NOT NULL AUTO_INCREMENT,
  `Nom_Valor` varchar(50) NOT NULL,
  `Nom_frecuencia` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_Valor`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

CREATE TABLE `funciones` (
  `ID_funcion` int(11) NOT NULL AUTO_INCREMENT,
  `Nom_funcion` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_funcion`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

CREATE TABLE `nomenclatura` (
  `ID_Nomen` int(11) NOT NULL AUTO_INCREMENT,
  `Nomenclatura` varchar(50) NOT NULL,
  `ID_Actividad` int(11) NOT NULL,
  `nom_actividad` varchar(50) NOT NULL,
  `ID_Procesos` int(11) NOT NULL,
  `Nom_Proceso` varchar(50) NOT NULL,
  `ID_Subproceso` int(11) NOT NULL,
  `Nom_Subproceso` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_Nomen`),
  KEY `ID_Actividad` (`ID_Actividad`),
  CONSTRAINT `nomenclatura_ibfk_1` FOREIGN KEY (`ID_Actividad`) REFERENCES `detalle_actividad` (`ID_Actividad`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

CREATE TABLE `nuevo_puesto` (
  `ID_Nuevo_Puesto` int(11) NOT NULL AUTO_INCREMENT,
  `Nuevo_Puesto` varchar(50) NOT NULL,
  `ID_Actividad` int(11) NOT NULL,
  `nom_actividad` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_Nuevo_Puesto`),
  KEY `ID_Actividad` (`ID_Actividad`),
  CONSTRAINT `nuevo_puesto_ibfk_1` FOREIGN KEY (`ID_Actividad`) REFERENCES `detalle_actividad` (`ID_Actividad`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

CREATE TABLE `procesos` (
  `ID_Procesos` int(11) NOT NULL AUTO_INCREMENT,
  `Nom_Procesos` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_Procesos`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

CREATE TABLE `procesos_consultas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `proceso` varchar(255) DEFAULT NULL,
  `subproceso` varchar(255) DEFAULT NULL,
  `actividad` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=256 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

CREATE TABLE `roles` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `rol` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

CREATE TABLE `sub_proceso` (
  `ID_subProcesos` int(11) NOT NULL AUTO_INCREMENT,
  `nom_Subproceso` varchar(150) NOT NULL,
  PRIMARY KEY (`ID_subProcesos`)
) ENGINE=InnoDB AUTO_INCREMENT=39 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

CREATE TABLE `taxonomina` (
  `ID_Taxonomina` int(11) NOT NULL AUTO_INCREMENT,
  `nom_taxonomina` varchar(50) NOT NULL,
  `ID_Actividad` int(11) NOT NULL,
  `nom_actividad` varchar(50) NOT NULL,
  `ID_proceso` int(11) NOT NULL,
  `nom_proceso` varchar(50) NOT NULL,
  `ID_Subproceso` int(11) NOT NULL,
  `nom_Subproceso` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_Taxonomina`),
  KEY `ID_Actividad` (`ID_Actividad`),
  KEY `ID_proceso` (`ID_proceso`),
  KEY `ID_Subproceso` (`ID_Subproceso`),
  CONSTRAINT `taxonomina_ibfk_1` FOREIGN KEY (`ID_Actividad`) REFERENCES `detalle_actividad` (`ID_Actividad`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `taxonomina_ibfk_2` FOREIGN KEY (`ID_proceso`) REFERENCES `procesos` (`ID_Procesos`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `taxonomina_ibfk_3` FOREIGN KEY (`ID_Subproceso`) REFERENCES `sub_proceso` (`ID_subProcesos`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

CREATE TABLE `tipo` (
  `ID_Tipo` int(11) NOT NULL AUTO_INCREMENT,
  `nom_tipo` varchar(100) NOT NULL,
  `ID_Actividad` int(11) NOT NULL,
  `nom_actividad` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_Tipo`),
  KEY `ID_Actividad` (`ID_Actividad`),
  CONSTRAINT `tipo_ibfk_1` FOREIGN KEY (`ID_Actividad`) REFERENCES `detalle_actividad` (`ID_Actividad`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

CREATE TABLE `unidad_negocio` (
  `ID_unidad_negocio` int(11) NOT NULL AUTO_INCREMENT,
  `nom_unidad_negocio` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_unidad_negocio`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

CREATE TABLE `usernames` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(10) NOT NULL,
  `rol_id` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `rol_id` (`rol_id`),
  CONSTRAINT `usernames_ibfk_1` FOREIGN KEY (`rol_id`) REFERENCES `roles` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

CREATE TABLE `usuario_cliente` (
  `ID_empleado` int(11) NOT NULL AUTO_INCREMENT,
  `Nombre` varchar(50) NOT NULL,
  `Apellido` varchar(50) NOT NULL,
  `Nom_Unidad_Negocio` varchar(50) NOT NULL,
  `Email` varchar(50) NOT NULL,
  `Area` varchar(50) NOT NULL,
  `Nom_Actividad` varchar(300) NOT NULL,
  `Nom_Nuevo_Puesto` varchar(50) NOT NULL,
  `Nom_Proceso` varchar(300) NOT NULL,
  `Nom_Direcciones` varchar(50) NOT NULL,
  `Nom_Subproceso` varchar(300) NOT NULL,
  `Nom_funcion` varchar(50) NOT NULL,
  `val_Frec` varchar(255) NOT NULL,
  `input` varchar(255) NOT NULL,
  `sistema` varchar(255) NOT NULL,
  `rol` varchar(100) NOT NULL,
  `tiempo` varchar(50) NOT NULL,
  `vol` varchar(50) NOT NULL,
  `t_h` varchar(100) NOT NULL,
  `ftes` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_empleado`)
) ENGINE=InnoDB AUTO_INCREMENT=148 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;;

INSERT INTO `consultas` (`ID`, `val_Frec`, `input`, `sistema`, `rol`, `tiempo`, `vol`, `t_h`, `ftes`, `estado`, `username_id`, `procesos_id`) VALUES
(0, '4', '123', '456', 'Ejecutar', '10', '2', '80', '0.5', '1', 2, 1),
(1, '', '', '', '', '', '', '', '', '0', 0, 2),
(2, '', '', '', '', '', '', '', '', '0', 0, 3),
(3, '', '', '', '', '', '', '', '', '0', 0, 4),
(4, '', '', '', '', '', '', '', '', '0', 0, 5),
(5, '', '', '', '', '', '', '', '', '0', 0, 6),
(6, '', '', '', '', '', '', '', '', '0', 0, 7),
(7, '', '', '', '', '', '', '', '', '0', 0, 8),
(8, '', '', '', '', '', '', '', '', '0', 0, 9),
(9, '', '', '', '', '', '', '', '', '0', 0, 10),
(10, '', '', '', '', '', '', '', '', '0', 0, 11),
(11, '', '', '', '', '', '', '', '', '0', 0, 12),
(12, '', '', '', '', '', '', '', '', '0', 0, 13),
(13, '', '', '', '', '', '', '', '', '0', 0, 14),
(14, '', '', '', '', '', '', '', '', '0', 0, 15),
(15, '', '', '', '', '', '', '', '', '0', 0, 16),
(16, '', '', '', '', '', '', '', '', '0', 0, 17),
(17, '', '', '', '', '', '', '', '', '0', 0, 18),
(18, '', '', '', '', '', '', '', '', '0', 0, 19),
(19, '', '', '', '', '', '', '', '', '0', 0, 20),
(20, '', '', '', '', '', '', '', '', '0', 0, 21),
(21, '', '', '', '', '', '', '', '', '0', 0, 22),
(22, '', '', '', '', '', '', '', '', '0', 0, 23),
(23, '', '', '', '', '', '', '', '', '0', 0, 24),
(24, '', '', '', '', '', '', '', '', '0', 0, 25),
(25, '', '', '', '', '', '', '', '', '0', 0, 26),
(26, '', '', '', '', '', '', '', '', '0', 0, 27),
(27, '', '', '', '', '', '', '', '', '0', 0, 28),
(28, '', '', '', '', '', '', '', '', '0', 0, 29),
(29, '', '', '', '', '', '', '', '', '0', 0, 30),
(31, '', '', '', '', '', '', '', '', '0', 0, 31),
(32, '', '', '', '', '', '', '', '', '0', 0, 32),
(33, '', '', '', '', '', '', '', '', '0', 0, 33),
(34, '', '', '', '', '', '', '', '', '0', 0, 34),
(35, '', '', '', '', '', '', '', '', '0', 0, 35),
(36, '', '', '', '', '', '', '', '', '0', 0, 36),
(37, '', '', '', '', '', '', '', '', '0', 0, 37),
(38, '', '', '', '', '', '', '', '', '0', 0, 38),
(39, '', '', '', '', '', '', '', '', '0', 0, 39),
(40, '', '', '', '', '', '', '', '', '0', 0, 40),
(41, '', '', '', '', '', '', '', '', '0', 0, 41),
(42, '', '', '', '', '', '', '', '', '0', 0, 42),
(43, '', '', '', '', '', '', '', '', '0', 0, 43),
(44, '', '', '', '', '', '', '', '', '0', 0, 44),
(45, '', '', '', '', '', '', '', '', '0', 0, 45),
(46, '', '', '', '', '', '', '', '', '0', 0, 46),
(47, '', '', '', '', '', '', '', '', '0', 0, 47),
(48, '', '', '', '', '', '', '', '', '0', 0, 48),
(49, '', '', '', '', '', '', '', '', '0', 0, 49),
(50, '', '', '', '', '', '', '', '', '0', 0, 50),
(51, '', '', '', '', '', '', '', '', '0', 0, 51),
(52, '', '', '', '', '', '', '', '', '0', 0, 52),
(53, '', '', '', '', '', '', '', '', '0', 0, 53),
(54, '', '', '', '', '', '', '', '', '0', 0, 54),
(55, '', '', '', '', '', '', '', '', '0', 0, 55),
(56, '', '', '', '', '', '', '', '', '0', 0, 56),
(57, '', '', '', '', '', '', '', '', '0', 0, 57),
(58, '', '', '', '', '', '', '', '', '0', 0, 58),
(59, '', '', '', '', '', '', '', '', '0', 0, 59),
(60, '', '', '', '', '', '', '', '', '0', 0, 60),
(61, '', '', '', '', '', '', '', '', '0', 0, 61),
(62, '', '', '', '', '', '', '', '', '0', 0, 62),
(63, '', '', '', '', '', '', '', '', '0', 0, 63),
(64, '', '', '', '', '', '', '', '', '0', 0, 64),
(65, '', '', '', '', '', '', '', '', '0', 0, 65),
(66, '', '', '', '', '', '', '', '', '0', 0, 66),
(67, '', '', '', '', '', '', '', '', '0', 0, 67),
(68, '', '', '', '', '', '', '', '', '0', 0, 68),
(69, '', '', '', '', '', '', '', '', '0', 0, 69),
(70, '', '', '', '', '', '', '', '', '0', 0, 70),
(71, '', '', '', '', '', '', '', '', '0', 0, 71),
(72, '', '', '', '', '', '', '', '', '0', 0, 72),
(73, '', '', '', '', '', '', '', '', '0', 0, 73),
(74, '', '', '', '', '', '', '', '', '0', 0, 74),
(75, '', '', '', '', '', '', '', '', '0', 0, 75),
(76, '', '', '', '', '', '', '', '', '0', 0, 76),
(77, '', '', '', '', '', '', '', '', '0', 0, 77),
(78, '', '', '', '', '', '', '', '', '0', 0, 78),
(79, '', '', '', '', '', '', '', '', '0', 0, 79),
(80, '', '', '', '', '', '', '', '', '0', 0, 80),
(81, '', '', '', '', '', '', '', '', '0', 0, 81),
(82, '', '', '', '', '', '', '', '', '0', 0, 82),
(83, '', '', '', '', '', '', '', '', '0', 0, 83),
(84, '', '', '', '', '', '', '', '', '0', 0, 84),
(85, '', '', '', '', '', '', '', '', '0', 0, 85),
(86, '', '', '', '', '', '', '', '', '0', 0, 86),
(87, '', '', '', '', '', '', '', '', '0', 0, 87),
(88, '', '', '', '', '', '', '', '', '0', 0, 88),
(89, '', '', '', '', '', '', '', '', '0', 0, 89),
(90, '', '', '', '', '', '', '', '', '0', 0, 90),
(91, '', '', '', '', '', '', '', '', '0', 0, 91),
(92, '', '', '', '', '', '', '', '', '0', 0, 92),
(93, '', '', '', '', '', '', '', '', '0', 0, 93),
(94, '', '', '', '', '', '', '', '', '0', 0, 94),
(95, '', '', '', '', '', '', '', '', '0', 0, 95),
(96, '', '', '', '', '', '', '', '', '0', 0, 96),
(97, '', '', '', '', '', '', '', '', '0', 0, 97),
(98, '', '', '', '', '', '', '', '', '0', 0, 98),
(99, '', '', '', '', '', '', '', '', '0', 0, 99),
(100, '', '', '', '', '', '', '', '', '0', 0, 100),
(101, '', '', '', '', '', '', '', '', '0', 0, 101),
(102, '', '', '', '', '', '', '', '', '0', 0, 102),
(103, '', '', '', '', '', '', '', '', '0', 0, 103),
(104, '', '', '', '', '', '', '', '', '0', 0, 104),
(105, '', '', '', '', '', '', '', '', '0', 0, 105),
(106, '', '', '', '', '', '', '', '', '0', 0, 106),
(107, '', '', '', '', '', '', '', '', '0', 0, 107),
(108, '', '', '', '', '', '', '', '', '0', 0, 108),
(109, '', '', '', '', '', '', '', '', '0', 0, 109),
(110, '', '', '', '', '', '', '', '', '0', 0, 110),
(111, '', '', '', '', '', '', '', '', '0', 0, 111),
(112, '', '', '', '', '', '', '', '', '0', 0, 112),
(113, '', '', '', '', '', '', '', '', '0', 0, 113),
(114, '', '', '', '', '', '', '', '', '0', 0, 114),
(115, '', '', '', '', '', '', '', '', '0', 0, 115),
(116, '', '', '', '', '', '', '', '', '0', 0, 116),
(117, '', '', '', '', '', '', '', '', '0', 0, 117),
(118, '', '', '', '', '', '', '', '', '0', 0, 118),
(119, '', '', '', '', '', '', '', '', '0', 0, 119),
(120, '', '', '', '', '', '', '', '', '0', 0, 120),
(121, '', '', '', '', '', '', '', '', '0', 0, 121),
(122, '', '', '', '', '', '', '', '', '0', 0, 122),
(123, '', '', '', '', '', '', '', '', '0', 0, 123),
(124, '', '', '', '', '', '', '', '', '0', 0, 124),
(125, '', '', '', '', '', '', '', '', '0', 0, 125),
(126, '', '', '', '', '', '', '', '', '0', 0, 126),
(127, '', '', '', '', '', '', '', '', '0', 0, 127),
(128, '', '', '', '', '', '', '', '', '0', 0, 128),
(129, '', '', '', '', '', '', '', '', '0', 0, 129),
(130, '', '', '', '', '', '', '', '', '0', 0, 130),
(131, '', '', '', '', '', '', '', '', '0', 0, 131),
(132, '', '', '', '', '', '', '', '', '0', 0, 132),
(133, '', '', '', '', '', '', '', '', '0', 0, 133),
(134, '', '', '', '', '', '', '', '', '0', 0, 134),
(135, '', '', '', '', '', '', '', '', '0', 0, 135),
(136, '', '', '', '', '', '', '', '', '0', 0, 136),
(137, '', '', '', '', '', '', '', '', '0', 0, 137),
(138, '', '', '', '', '', '', '', '', '0', 0, 138),
(139, '', '', '', '', '', '', '', '', '0', 0, 139),
(140, '', '', '', '', '', '', '', '', '0', 0, 140),
(141, '', '', '', '', '', '', '', '', '0', 0, 141),
(142, '', '', '', '', '', '', '', '', '0', 0, 142),
(143, '', '', '', '', '', '', '', '', '0', 0, 143),
(144, '', '', '', '', '', '', '', '', '0', 0, 144),
(145, '', '', '', '', '', '', '', '', '0', 0, 145),
(146, '', '', '', '', '', '', '', '', '0', 0, 146),
(147, '', '', '', '', '', '', '', '', '0', 0, 147),
(148, '', '', '', '', '', '', '', '', '0', 0, 148);

INSERT INTO `detalle_actividad` (`ID_Actividad`, `nom_actividad`, `Entregable`, `sistema`, `Descripcion`) VALUES
(1, '...', '', '', ''),
(2, 'Actualizar con nuevas SolP que no tienen asignació', '', '', ''),
(3, 'Actualizar contrato', '', '', ''),
(4, 'Actualizar estatus de servicio', '', '', ''),
(5, 'Actualizar lista', '', '', ''),
(6, 'Asignar comprador y notificar al comprador', '', '', ''),
(7, 'Asignar SolP a compradores por grupo de compra', '', '', ''),
(8, 'Atender a proveedores directamente (Corp)', '', '', ''),
(9, 'Atender consulta o canalizar al área correspondien', '', '', ''),
(10, 'Autorizar tarifas Fletes', '', '', ''),
(11, 'Buscar proveedores alternos', '', '', ''),
(12, 'Capturar tarifas Fletes', '', '', ''),
(13, 'Cargar información de proveedores en Excel', '', '', ''),
(14, 'Cerrar acuerdo con comprador', '', '', ''),
(15, 'Comparar año anterior con año actual para evaluar ', '', '', ''),
(16, 'Comparar listado actual con listado pasado', '', '', ''),
(17, 'Consolidar en formato predefinido', '', '', ''),
(18, 'Consolidar en un Excel', '', '', ''),
(19, 'Consolidar evaluaciones y enviar al SGC', '', '', ''),
(20, 'Consolidar información', '', '', ''),
(21, 'Consolidar reportes en un archivo', '', '', ''),
(22, 'Coordinar con almacén si se requiere otra requisición (para ingresar y manipular mercancía)', '', '', ''),
(23, 'Coordinar visita', '', '', ''),
(24, 'Coordinar visita a proveedores', '', '', ''),
(25, 'Corregir contrato', '', '', ''),
(26, 'Crear contrato', '', '', ''),
(27, 'Dar seguimiento', '', '', ''),
(28, 'Dar seguimiento a la orden de compra', '', '', ''),
(29, 'Definir convenio de retiro de compra', '', '', ''),
(30, 'Definir posibles compradores', '', '', ''),
(31, 'Definir posibles compradores de chatarra', '', '', ''),
(32, 'Determinar mejor opción', '', '', ''),
(33, 'Determinar tipo de unidad', '', '', ''),
(34, 'Documentar la lista de empaque', '', '', ''),
(35, 'Elaborar orden de compra', '', '', ''),
(36, 'Elaborar orden de compra', '', '', ''),
(37, 'Enlistar proveedores', '', '', ''),
(38, 'Envase de desechos: Solicitar aprobación del área ', '', '', ''),
(39, 'Enviar a Dirección Ejecutiva', '', '', ''),
(40, 'Enviar archivo ', '', '', ''),
(41, 'Enviar calificaciones a proyectos', '', '', ''),
(42, 'Enviar catálogo de equipo (si aplica)', '', '', ''),
(43, 'Enviar contrato y documentación para validación', '', '', ''),
(44, 'Enviar convenio a aprobación', '', '', ''),
(45, 'Enviar formato y solicitar evaluación', '', '', ''),
(46, 'Enviar invitación', '', '', ''),
(47, 'Enviar invitación de licitación', '', '', ''),
(48, 'Enviar justificación de calificación (si aplica)', '', '', ''),
(49, 'Enviar listado a validación', '', '', ''),
(50, 'Enviar propuesta al área técnica, contraloría e in', '', '', ''),
(51, 'Enviar reporte', '', '', ''),
(52, 'Enviar reportes', '', '', ''),
(53, 'Enviar respuesta', '', '', ''),
(54, 'Evaluar y asignar calificación', '', '', ''),
(55, 'Exportación temporal: Fumigar equipo y consolidar ', '', '', ''),
(56, 'Exportación temporal: Solicitar información para g', '', '', ''),
(57, 'Firmar contrato', '', '', ''),
(58, 'Generar cuadro comparativo', '', '', ''),
(59, 'Generar pedido', '', '', ''),
(60, 'Generar pedido (Se adjunta el PDF de validación)', '', '', ''),
(61, 'Generar petición de oferta en SAP', '', '', ''),
(62, 'Generar petición de oferta por correo electrónico', '', '', ''),
(63, 'Hacer modificaciones (si se requiere)', '', '', ''),
(64, 'Imprimir y firmar catálogo', '', '', ''),
(65, 'Liberar contrato marco', '', '', ''),
(66, 'Liberar pedido', '', '', ''),
(67, 'Listar compras de más de 500,000 mxn', '', '', ''),
(68, 'Llenar contrato', '', '', ''),
(69, 'Llenar métricas de evaluación', '', '', ''),
(70, 'Llevar a cabo cierre de auditoría', '', '', ''),
(71, 'Medir cumplimiento de proveedores (tiempos de entrega)', '', '', ''),
(72, 'Monitorear colocaciones y entregas', '', '', ''),
(73, 'Negocación y retroalimentación con proveedores', '', '', ''),
(74, 'Negociar con proveedor', '', '', ''),
(75, 'Negociar condiciones comerciales', '', '', ''),
(76, 'Negociar propuesta con compradores según las validaciones de las áreas', '', '', ''),
(77, 'Negociar tarifas Fletes', '', '', ''),
(78, 'Negociar y proponer nuevo precio objetivo (si aplica)', '', '', ''),
(79, 'Negociar y seleccionar proveedor', '', '', ''),
(80, 'Notificación de ingenio:  Seleccionar comprador y condiciones de compra', '', '', ''),
(81, 'Notificación de ingenio: Notificar la venta a lista de compradores', '', '', ''),
(82, 'Notificar a almacén para coordinar descarga', '', '', ''),
(83, 'Notificar a ingenios comprador seleccionado, condiciones de pago, precio y volumen', '', '', ''),
(84, 'Notificar acuerdo a los ingenios', '', '', ''),
(85, 'Notificar al agente aduanal el transportista seleccionado', '', '', ''),
(86, 'Notificar al almacén el comprador designado', '', '', ''),
(87, 'Notificar al almacén el comprador y precio designado', '', '', ''),
(88, 'Notificar al proveedor', '', '', ''),
(89, 'Notificar al seguro', '', '', ''),
(90, 'Notificar alta', '', '', ''),
(91, 'Notificar bloqueo', '', '', ''),
(92, 'Notificar la modificación', '', '', ''),
(93, 'Notificar precio de compra al almacén', '', '', ''),
(94, 'Notificar precio de compra al almacén', '', '', ''),
(95, 'Notificar rechazo', '', '', ''),
(96, 'Notificar rechazo de liberación', '', '', ''),
(97, 'Presentar a la auditoría', '', '', ''),
(98, 'Presentar departamentos a evaluar y auditores', '', '', ''),
(99, 'Proporcionar documentación para carta porte', '', '', ''),
(100, 'Prospectar fletes disponibles', '', '', ''),
(101, 'Realizar alta del DM', '', '', ''),
(102, 'Realizar bloqueo', '', '', ''),
(103, 'Realizar conferencia', '', '', ''),
(104, 'Realizar evaluación (Si aplica)', '', '', ''),
(105, 'Realizar formato de acción correctiva', '', '', ''),
(106, 'Realizar modificación del DM', '', '', ''),
(107, 'Realizar venta spot', '', '', ''),
(108, 'Realizar visita', '', '', ''),
(109, 'Recibir actualización de precio de compra', '', '', ''),
(110, 'Recibir autorización técnica', '', '', ''),
(111, 'Recibir confirmación de la orden de compra', '', '', ''),
(112, 'Recibir evaluación', '', '', ''),
(113, 'Recibir evaluaciones del SGC', '', '', ''),
(114, 'Recibir notificación de auditoria', '', '', ''),
(115, 'Recibir propuesta de proveedor', '', '', ''),
(116, 'Recibir propuesta de proveedores', '', '', ''),
(117, 'Recibir propuestas de posibles compradores', '', '', ''),
(118, 'Recibir propuestas y seleccionar comprador', '', '', ''),
(119, 'Recibir reportes de agentes aduanales (se reciben del contacto de agencias aduanales del ejecutivo que tiene la cuenta)', '', '', ''),
(120, 'Recibir retroalimentación del área de proyectos en cuanto a la calificación de los proveedores (calificación integral)', '', '', ''),
(121, 'Recibir solicitud de alta', '', '', ''),
(122, 'Recibir solicitud de bloqueo', '', '', ''),
(123, 'Recibir solicitud de consulta', '', '', ''),
(124, 'Recibir solicitud de modificación', '', '', ''),
(125, 'Recibir solicitud de venta de bagazo (de ingenios o comprador)', '', '', ''),
(126, 'Recibir solicitud del área de proyectos', '', '', ''),
(127, 'Recibir solicitud y propuestas', '', '', ''),
(128, 'Recibir SolP', '', '', ''),
(129, 'Recibir validación técnica', '', '', ''),
(130, 'Recibir validación técnica (como anexo en la OC)', '', '', ''),
(131, 'Recibir y registrar factura', '', '', ''),
(132, 'Recibir y revisar propuestas de compra de equipo', '', '', ''),
(133, 'Recibir y validar documentación', '', '', ''),
(134, 'Recibir y validar reporte final de las áreas y si esta bien notificar al área para que haga el envío a economía', '', '', ''),
(135, 'Recopilar consolidaciones mensuales (evaluaciones) y documentación a revisar', '', '', ''),
(136, 'Recuperar información de tiempos de ciclo de compra', '', '', ''),
(137, 'Recuperar información en SAP', '', '', ''),
(138, 'Recuperar listado de SolP', '', '', ''),
(139, 'Registrar proveedores con resultados positivos', '', '', ''),
(140, 'Reportar comentarios de la visita', '', '', ''),
(141, 'Resguardar catálogo', '', '', ''),
(142, 'Resguardar evaluación', '', '', ''),
(143, 'Resguardar evaluaciones y métricas', '', '', ''),
(144, 'Revisar autorización técnica', '', '', ''),
(145, 'Revisar comparativo y propuesta proporcionada', '', '', ''),
(146, 'Revisar comparativo y propuesta proporcionada (Decisión de compra)', '', '', ''),
(147, 'Revisar contrato firmado', '', '', ''),
(148, 'Revisar información proporcionada', '', '', ''),
(149, 'Seleccionar proveedor', '', '', ''),
(150, 'Seleccionar proveedores a visitar', '', '', ''),
(151, 'Seleccionar proveedores más frecuentes', '', '', ''),
(152, 'Si no es igual, se hace observación a ingenio para que corrijan la informacion o soliciten aclaración con ejecutivos adu', '', '', ''),
(153, 'Solicitar activación', '', '', ''),
(154, 'Solicitar cotización al proveedor y visto bueno usuario', '', '', ''),
(155, 'Solicitar documentación vigente (si aplica)', '', '', ''),
(156, 'Solicitar información correcta', '', '', ''),
(157, 'Solicitar nueva cotización/propuesta  ', '', '', ''),
(158, 'Solicitar propuestas de compra', '', '', ''),
(159, 'Solicitar validación', '', '', ''),
(160, 'Solicitar validación con los ingenios', '', '', ''),
(161, 'Tomar decisión de compra', '', '', ''),
(162, 'Validar con ususarios y almacén / Retroalimentación proveedores', '', '', ''),
(163, 'Validar documentación', '', '', ''),
(164, 'Validar evaluaciones del proveedor', '', '', ''),
(165, 'Validar los registros de las gerencias administrativas y/o contabilidad vs los reportes aduanales', '', '', ''),
(166, 'Validar posible transportista', '', '', ''),
(167, 'Validar propuesta del proveedor', '', '', ''),
(168, 'Validar si se incluyen en la lista', '', '', ''),
(169, 'Verificar salidas o cambio de proveedor', '', '', ''),
(170, 'Visitar instalaciones', '', '', '');

INSERT INTO `direcciones` (`ID_Direccion`, `Nom_Direccion`) VALUES
(1, '...'),
(2, 'Direccion de Cadena de Suministro'),
(3, 'Dirección de Finanzas'),
(4, 'Dirección de Capital Humano');

INSERT INTO `entrega` (`ID_entrega`, `nom_entrega`) VALUES
(1, 'SI REMOTA'),
(3, 'NO SITIO');

INSERT INTO `eventos` (`ID_Eventos`, `Eventual`, `Por_Eventos`, `Continuos`, `Mensual`) VALUES
(2, '...', '...', '...', '...');

INSERT INTO `frecuencia` (`ID_Valor`, `Nom_Valor`, `Nom_frecuencia`) VALUES
(2, '4', 'Semanal'),
(3, '1', 'Mensual'),
(4, '12', 'Anual');

INSERT INTO `funciones` (`ID_funcion`, `Nom_funcion`) VALUES
(1, '...'),
(2, 'Abastecimientos');

INSERT INTO `nomenclatura` (`ID_Nomen`, `Nomenclatura`, `ID_Actividad`, `nom_actividad`, `ID_Procesos`, `Nom_Proceso`, `ID_Subproceso`, `Nom_Subproceso`) VALUES
(1, '...', 1, '...', 1, '...', 1, '...');

INSERT INTO `nuevo_puesto` (`ID_Nuevo_Puesto`, `Nuevo_Puesto`, `ID_Actividad`, `nom_actividad`) VALUES
(8, '...', 1, '...'),
(10, 'Analista de abasto', 1, '...');

INSERT INTO `procesos` (`ID_Procesos`, `Nom_Procesos`) VALUES
(1, '...'),
(2, 'Administrar proveedores'),
(3, 'Atender consultas internas y externas'),
(4, 'Gestión/Monitoreo de Indicadores y Reportes '),
(5, 'Gestionar auditorías'),
(6, 'Gestionar compras de materiales'),
(7, 'Gestionar compras de servicios'),
(8, 'Gestionar Contratos'),
(9, 'Gestionar Datos Maestros de Proveedores'),
(10, 'Gestionar venta de chatarra, bagazo y equipo'),
(11, 'Logística de materiales/equipos');

INSERT INTO `procesos_consultas` (`id`, `proceso`, `subproceso`, `actividad`) VALUES
(1, 'Gestionar Contratos', 'Gestionar contrato de servicios administrativos y de zafra', 'Firmar contrato'),
(2, 'Gestionar Contratos', 'Gestionar contrato de transportistas', 'Recibir solicitud y propuestas'),
(3, 'Gestionar Contratos', 'Gestionar contrato de transportistas', 'Validar posible transportista'),
(4, 'Gestionar Contratos', 'Gestionar contrato de transportistas', 'Visitar instalaciones'),
(5, 'Gestionar Contratos', 'Gestionar contrato de transportistas', 'Validar documentación'),
(6, 'Gestionar Contratos', 'Gestionar contrato de transportistas', 'Solicitar información correcta'),
(7, 'Gestionar Contratos', 'Gestionar contrato de transportistas', 'Llenar contrato'),
(8, 'Gestionar Contratos', 'Gestionar contrato de transportistas', 'Enviar contrato y documentación para validación'),
(9, 'Gestionar Contratos', 'Gestionar contrato de transportistas', 'Corregir contrato'),
(10, 'Gestionar Contratos', 'Gestionar contrato de transportistas', 'Firmar contrato'),
(11, 'Gestionar Contratos', 'Gestionar contratos de bodegas de azúcar', 'Validar propuesta del proveedor'),
(12, 'Gestionar Contratos', 'Gestionar contratos de bodegas de azúcar', 'Solicitar nueva cotización/propuesta'),
(13, 'Gestionar Contratos', 'Gestionar contratos de bodegas de azúcar', 'Negociar con proveedor'),
(14, 'Gestionar Contratos', 'Gestionar contratos de bodegas de azúcar', 'Recibir y validar documentación'),
(15, 'Gestionar Contratos', 'Gestionar contratos de bodegas de azúcar', 'Solicitar información correcta'),
(16, 'Gestionar Contratos', 'Gestionar contratos de bodegas de azúcar', 'Revisar contrato firmado'),
(17, 'Gestionar Contratos', 'Gestionar contratos de bodegas de azúcar', 'Actualizar contrato'),
(18, 'Gestionar Contratos', 'Gestionar contratos de bodegas de azúcar', 'Llenar contrato'),
(19, 'Gestionar Contratos', 'Gestionar contratos de bodegas de azúcar', 'Firmar contrato'),
(20, 'Gestionar Contratos', 'Gestionar contratos de bodegas de azúcar', 'Enviar contrato y documentación para validación'),
(21, 'Gestionar Contratos', 'Gestionar contratos de bodegas de azúcar', 'Corregir contrato'),
(22, 'Gestionar Contratos', 'Gestionar contratos de bodegas de azúcar', 'Firmar contrato'),
(23, 'Gestionar Contratos', 'Gestionar contrato de servicios administrativos y de zafra', 'Recibir propuesta de proveedor'),
(24, 'Gestionar Contratos', 'Gestionar contrato de servicios administrativos y de zafra', 'Negociar condiciones comerciales'),
(25, 'Gestionar Contratos', 'Gestionar contrato de servicios administrativos y de zafra', 'Determinar mejor opción'),
(26, 'Gestionar Contratos', 'Gestionar contrato de servicios administrativos y de zafra', 'Llenar contrato'),
(27, 'Gestionar Contratos', 'Gestionar contrato de servicios administrativos y de zafra', 'Validar documentación'),
(28, 'Gestionar Contratos', 'Gestionar contrato de servicios administrativos y de zafra', 'Solicitar información correcta'),
(29, 'Gestionar Contratos', 'Gestionar contrato de servicios administrativos y de zafra', 'Enviar contrato y documentación para validación'),
(30, 'Gestionar Contratos', 'Gestionar contrato de servicios administrativos y de zafra', 'Corregir contrato'),
(31, 'Gestionar Contratos', 'Gestionar contrato marco SAP', 'Enviar invitación de licitación'),
(32, 'Gestionar Contratos', 'Gestionar contrato marco SAP', 'Negociar y seleccionar proveedor'),
(33, 'Gestionar Contratos', 'Gestionar contrato marco SAP', 'Crear contrato'),
(34, 'Gestionar Contratos', 'Gestionar contrato marco SAP', 'Liberar contrato marco'),
(35, 'Gestionar Contratos', 'Gestionar contrato marco SAP', 'Buscar proveedores alternos'),
(36, 'Gestionar Datos Maestros de Proveedores', 'Gestionar alta de DM de Proveedores', 'Recibir solicitud de alta'),
(37, 'Gestionar Datos Maestros de Proveedores', 'Gestionar alta de DM de Proveedores', 'Revisar información proporcionada'),
(38, 'Gestionar Datos Maestros de Proveedores', 'Gestionar alta de DM de Proveedores', 'Solicitar información correcta'),
(39, 'Gestionar Datos Maestros de Proveedores', 'Gestionar alta de DM de Proveedores', 'Realizar alta del DM'),
(40, 'Gestionar Datos Maestros de Proveedores', 'Gestionar alta de DM de Proveedores', 'Notificar alta'),
(41, 'Gestionar Datos Maestros de Proveedores', 'Gestionar modificación de DM de Proveedores', 'Recibir solicitud de modificación'),
(42, 'Gestionar Datos Maestros de Proveedores', 'Gestionar modificación de DM de Proveedores', 'Revisar información proporcionada'),
(43, 'Gestionar Datos Maestros de Proveedores', 'Gestionar modificación de DM de Proveedores', 'Solicitar información correcta'),
(44, 'Gestionar Datos Maestros de Proveedores', 'Gestionar modificación de DM de Proveedores', 'Realizar modificación del DM'),
(45, 'Gestionar Datos Maestros de Proveedores', 'Gestionar modificación de DM de Proveedores', 'Notificar la modificación'),
(46, 'Gestionar Datos Maestros de Proveedores', 'Gestionar alta de DM de Proveedores (Portal)', 'Recibir solicitud de alta'),
(47, 'Gestionar Datos Maestros de Proveedores', 'Gestionar alta de DM de Proveedores (Portal)', 'Notificar alta'),
(48, 'Gestionar Datos Maestros de Proveedores', 'Gestionar alta de DM de Proveedores (Portal)', 'Revisar información proporcionada'),
(49, 'Gestionar Datos Maestros de Proveedores', 'Gestionar alta de DM de Proveedores (Portal)', 'Solicitar información correcta'),
(50, 'Gestionar Datos Maestros de Proveedores', 'Gestionar alta de DM de Proveedores (Portal)', 'Realizar alta del DM'),
(51, 'Gestionar Datos Maestros de Proveedores', 'Gestionar alta de DM de Proveedores (Portal)', 'Solicitar validación'),
(52, 'Gestionar Datos Maestros de Proveedores', 'Gestionar alta de DM de Proveedores (Portal)', 'Notificar al proveedor'),
(53, 'Gestionar Datos Maestros de Proveedores', 'Gestionar alta de DM de Proveedores (Portal)', 'Solicitar activación'),
(54, 'Gestionar Datos Maestros de Proveedores', 'Gestionar bloqueo de proveedores', 'Recibir solicitud de bloqueo'),
(55, 'Gestionar Datos Maestros de Proveedores', 'Gestionar bloqueo de proveedores', 'Realizar bloqueo\r\n'),
(56, 'Gestionar Datos Maestros de Proveedores', 'Gestionar bloqueo de proveedores', 'Notificar bloqueo'),
(57, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Recibir SolP'),
(58, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Generar petición de oferta en SAP'),
(59, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Recibir propuesta de proveedores'),
(60, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Negociación y retroalimentación con proveedores'),
(61, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Generar cuadro comparativo'),
(62, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Validar con usuarios y almacén / Retroalimentación proveedores'),
(63, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Tomar decisión de compra'),
(64, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Generar pedido'),
(65, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Liberar pedido\r\n'),
(66, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Liberar pedido'),
(67, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Notificar rechazo de liberación'),
(68, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Recibir confirmación de la orden de compra'),
(69, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Dar seguimiento a la orden de compra'),
(70, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Recibir y registrar factura'),
(71, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Recibir SolP'),
(72, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Generar petición de oferta en SAP'),
(73, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Recibir propuesta de proveedores'),
(74, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Negociación y retroalimentación con proveedores'),
(75, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Generar cuadro comparativo'),
(76, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Validar con usuarios y almacén / Retroalimentación proveedores'),
(77, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Tomar decisión de compra'),
(78, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Generar pedido'),
(79, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Liberar pedido'),
(80, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Notificar rechazo de liberación'),
(81, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Recibir confirmación de la orden de compra'),
(82, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Dar seguimiento a la orden de compra'),
(83, 'Gestionar compras de materiales', 'Gestionar pedidos estándar (Compras menores)', 'Recibir y registrar factura'),
(84, 'Gestionar compras de materiales', 'Gestionar pedidos con convenio (Contrato Marco)', 'Recibir SolP'),
(85, 'Gestionar compras de materiales', 'Gestionar pedidos con convenio (Contrato Marco)', 'Generar pedido'),
(86, 'Gestionar compras de materiales', 'Gestionar pedidos con convenio (Contrato Marco)', 'Recibir confirmación de la orden de compra'),
(87, 'Gestionar compras de materiales', 'Gestionar pedidos con convenio (Contrato Marco)', 'Dar seguimiento a la orden de compra'),
(88, 'Gestionar compras de materiales', 'Gestionar pedidos con convenio (Contrato Marco)', 'Recibir y registrar factura'),
(89, 'Gestionar compras de materiales', 'Gestionar pedidos por asignación directa', 'Recibir SolP'),
(90, 'Gestionar compras de materiales', 'Gestionar pedidos por asignación directa', 'Recibir autorización técnica'),
(91, 'Gestionar compras de materiales', 'Gestionar pedidos por asignación directa', 'Generar pedido'),
(92, 'Gestionar compras de materiales', 'Gestionar pedidos por asignación directa', 'Liberar pedido'),
(93, 'Gestionar compras de materiales', 'Gestionar pedidos por asignación directa', 'Liberar pedido'),
(94, 'Gestionar compras de materiales', 'Gestionar pedidos por asignación directa', 'Notificar rechazo'),
(95, 'Gestionar compras de materiales', 'Gestionar pedidos por asignación directa', 'Recibir confirmación de la orden de compra'),
(96, 'Gestionar compras de materiales', 'Gestionar pedidos por asignación directa', 'Dar seguimiento a la orden de compra'),
(97, 'Gestionar compras de materiales', 'Gestionar pedidos por asignación directa', 'Recibir y registrar factura'),
(98, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Recibir SolP'),
(99, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Generar petición de oferta por correo electrónico'),
(100, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Recibir propuestas de proveedores'),
(101, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Generar cuadro comparativo'),
(102, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Revisar comparativo y propuesta proporcionada (Decisión de compra)'),
(103, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Recibir validación técnica (como anexo en la OC)'),
(104, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Elaborar orden de compra'),
(105, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Liberar pedido'),
(106, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Liberar pedido'),
(107, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Notificar rechazo'),
(108, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Recibir confirmación de la orden de compra'),
(109, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Recibir SolP'),
(110, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Generar petición de oferta por correo electrónico'),
(111, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Recibir propuestas de proveedores'),
(112, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Generar cuadro comparativo'),
(113, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Revisar comparativo y propuesta proporcionada'),
(114, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Recibir validación técnica (como anexo en la OC)'),
(115, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Elaborar orden de compra'),
(116, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Liberar pedido\r\n'),
(117, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Notificar rechazo'),
(118, 'Gestionar compras de servicios', 'Gestionar pedidos estándar (Compras menores)', 'Recibir confirmación de la orden de compra'),
(119, 'Gestionar compras de servicios', 'Gestionar pedidos con convenio (Contrato Marco)', 'Recibir SolP'),
(120, 'Gestionar compras de servicios', 'Gestionar pedidos con convenio (Contrato Marco)', 'Solicitar cotización al proveedor y visto bueno usuario'),
(121, 'Gestionar compras de servicios', 'Gestionar pedidos con convenio (Contrato Marco)', 'Generar pedido'),
(122, 'Gestionar compras de servicios', 'Gestionar pedidos con convenio (Contrato Marco)', 'Liberar pedido'),
(123, 'Gestionar compras de servicios', 'Gestionar pedidos con convenio (Contrato Marco)', 'Recibir confirmación de la orden de compra'),
(124, 'Gestionar compras de servicios', 'Gestionar pedidos por asignación directa', 'Recibir SolP '),
(125, 'Gestionar compras de servicios', 'Gestionar pedidos por asignación directa', 'Revisar autorización técnica'),
(126, 'Gestionar compras de servicios', 'Gestionar pedidos por asignación directa', 'Generar pedido (Se adjunta el PDF de validación)'),
(127, 'Gestionar compras de servicios', 'Gestionar pedidos por asignación directa', 'Liberar pedido'),
(128, 'Gestionar compras de servicios', 'Gestionar pedidos por asignación directa', 'Liberar pedido'),
(129, 'Gestionar compras de servicios', 'Gestionar pedidos por asignación directa', 'Notificar rechazo'),
(130, 'Gestionar compras de servicios', 'Gestionar pedidos por asignación directa', 'Recibir confirmación de la orden de compra'),
(131, 'Gestionar compras de servicios', 'Gestionar pedidos por concurso (proyectos)', 'Recibir SolP'),
(132, 'Gestionar compras de servicios', 'Gestionar pedidos por concurso (proyectos)', 'Recibir solicitud del área de proyectos'),
(133, 'Gestionar compras de servicios', 'Gestionar pedidos por concurso (proyectos)', 'Enviar invitación'),
(134, 'Gestionar compras de servicios', 'Gestionar pedidos por concurso (proyectos)', 'Realizar conferencia'),
(135, 'Gestionar compras de servicios', 'Gestionar pedidos por concurso (proyectos)', 'Recibir propuestas de proveedores'),
(136, 'Gestionar compras de servicios', 'Gestionar pedidos por concurso (proyectos)', 'Generar cuadro comparativo'),
(137, 'Gestionar compras de servicios', 'Gestionar pedidos por concurso (proyectos)', 'Revisar comparativo y propuesta proporcionada (Decisión de compra)'),
(138, 'Gestionar compras de servicios', 'Gestionar pedidos por concurso (proyectos)', 'Recibir validación técnica'),
(139, 'Gestionar compras de servicios', 'Gestionar pedidos por concurso (proyectos)', 'Elaborar orden de compra'),
(140, 'Gestionar compras de servicios', 'Gestionar pedidos por concurso (proyectos)', 'Liberar pedido'),
(141, 'Gestionar compras de servicios', 'Gestionar pedidos por concurso (proyectos)', 'Notificar rechazo'),
(142, 'Gestionar compras de servicios', 'Gestionar pedidos por concurso (proyectos)', 'Recibir confirmación de la orden de compra'),
(143, 'Gestionar compras de servicios', 'Evaluar proveedores de servicios de proyectos ', 'Enlistar proveedores'),
(144, 'Gestionar compras de servicios', 'Evaluar proveedores de servicios de proyectos ', 'Evaluar y asignar calificación'),
(145, 'Gestionar compras de servicios', 'Evaluar proveedores de servicios de proyectos ', 'Enviar calificaciones a proyectos'),
(146, 'Gestionar compras de servicios', 'Evaluar proveedores de servicios de proyectos ', 'Enviar justificación de calificación (si aplica)'),
(147, 'Gestionar compras de servicios', 'Evaluar proveedores de servicios de proyectos ', 'Recibir retroalimentación del área de proyectos en cuanto a la calificación de los proveedores (calificación integral)'),
(148, 'Gestionar compras de servicios', 'Evaluar proveedores de servicios de proyectos ', 'Resguardar evaluación');

INSERT INTO `roles` (`ID`, `rol`) VALUES
(1, 'administrador'),
(2, 'visita');

INSERT INTO `sub_proceso` (`ID_subProcesos`, `nom_Subproceso`) VALUES
(1, '...'),
(2, 'Actualizar catalogo de proveedores de insumos'),
(3, 'Asignación de SolP'),
(4, 'Atender consultas generales '),
(5, 'Ciclo de compra y cumplimiento de proveedores'),
(6, 'Evaluar proveedores de servicios de proyectos '),
(7, 'Evaluar proveedores SGC (Reevaluación)'),
(8, 'Fletes, traslado de proveedores nacionales/talleres/Ingenios'),
(9, 'Fletes, traslado nacional de proveedores extranjeros (Importación)'),
(10, 'Gestionar alta de DM de Proveedores'),
(11, 'Gestionar alta de DM de Proveedores (Portal)'),
(12, 'Gestionar auditoría interna y externa'),
(13, 'Gestionar bloqueo de proveedores'),
(14, 'Gestionar catálogo de proveedores de servicios (Excel)'),
(15, 'Gestionar compras de importación'),
(16, 'Gestionar contrato de servicios administrativos y de zafra'),
(17, 'Gestionar contrato de transportistas'),
(18, 'Gestionar contrato marco SAP'),
(19, 'Gestionar contratos de bodegas de azúcar'),
(20, 'Gestionar estrategia de fletes'),
(21, 'Gestionar modificación de DM de Proveedores'),
(22, 'Gestionar pedidos con convenio (Contrato Marco)'),
(23, 'Gestionar pedidos estándar (Compras mayores)'),
(24, 'Gestionar pedidos estándar (Compras menores)'),
(25, 'Gestionar pedidos por asignación directa'),
(26, 'Gestionar pedidos por concurso (proyectos)'),
(27, 'Realizar alta en catalogo de proveedores de insumos (SGC) '),
(28, 'Realizar visita de seguimiento a proveedores'),
(29, 'Realizar visitas con nuevos proveedores de insumos (SGC) (Evaluación)'),
(30, 'Realizar visitas con proveedores de insumos existentes (SGC)'),
(31, 'Reporte anual de importaciones (Prosec)'),
(32, 'Reporte de servicios'),
(33, 'Reporte mensual ejecutivo'),
(34, 'Seguimiento de colocación de indicadores y de entregas'),
(35, 'Venta de bagazo'),
(36, 'Venta de chatarra (Spot)'),
(37, 'Venta de chatarra y envase de desechos'),
(38, 'Venta de equipo de fabrica');

INSERT INTO `taxonomina` (`ID_Taxonomina`, `nom_taxonomina`, `ID_Actividad`, `nom_actividad`, `ID_proceso`, `nom_proceso`, `ID_Subproceso`, `nom_Subproceso`) VALUES
(1, '...', 1, '...', 1, '...', 1, '...');

INSERT INTO `tipo` (`ID_Tipo`, `nom_tipo`, `ID_Actividad`, `nom_actividad`) VALUES
(1, '...', 1, '...');

INSERT INTO `unidad_negocio` (`ID_unidad_negocio`, `nom_unidad_negocio`) VALUES
(1, '...'),
(2, 'SAISA'),
(3, 'ITVSA'),
(4, 'IALMSA'),
(5, 'IPSLSA'),
(6, 'CIS'),
(7, 'PIASA');

INSERT INTO `usernames` (`ID`, `username`, `password`, `rol_id`) VALUES
(1, 'Administrador', 'Pi@5a.2E', 1),
(2, 'cliente', '1234', 2),
(4, 'cliente2', 'piasa123', 2);

INSERT INTO `usuario_cliente` (`ID_empleado`, `Nombre`, `Apellido`, `Nom_Unidad_Negocio`, `Email`, `Area`, `Nom_Actividad`, `Nom_Nuevo_Puesto`, `Nom_Proceso`, `Nom_Direcciones`, `Nom_Subproceso`, `Nom_funcion`, `val_Frec`, `input`, `sistema`, `rol`, `tiempo`, `vol`, `t_h`, `ftes`) VALUES
(147, 'Julio', 'Aguilar', 'SAISA', 'julio.ac@abc.com', 'La que sea', 'Firmar contrato', 'Analista de abasto', 'Gestionar Contratos', 'Direccion de Cadena de Suministro', 'Gestionar contrato de servicios administrativos y de zafra', 'Abastecimientos', '4', '123', '456', 'Ejecutar', '10', '2', '80', '0.5');



/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;